name: my-contacts
services:
  backend:
    build: ./backend
    restart: always
    depends_on:
      - database
    volumes:
      - ./backend:/my-contacts/backend
      - node_modules:/my-contacts/backend/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network


  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mycontacts_pw
      POSTGRES_USER: mycontacts_user
      POSTGRES_DB: mycontacts_db
    volumes:
      - type: bind
        source: ./database/data
        target: /var/lib/postgres/data
        bind:
          create_host_path: true
      - type: bind
        source: ./database/initdb
        target: /docker-entrypoint-initdb.d/create_tables.sql
        bind:
          create_host_path: true
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: always

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
