name: my-contacts
services:
  backend:
    build: ./backend
    working_dir: /my-contacts/backend
    volumes:
      - ./backend:/my-contacts/backend
    networks:
      - back-tier

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mycontacts_pw
      POSTGRES_USER: mycontacts_user
      POSTGRES_DB: mycontacts_db
    volumes:
      - type: bind
        source: ./database/data
        target: /var/lib/postgres/data
        bind:
          create_host_path: true
      - ./database/initdb:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    restart: unless-stoped


networks:
  back-tier: {}
