name: my-contacts

services:

  # Backend api for my-contacts web app
  backend:
    build: ./backend
    restart: always
    depends_on:
      - database
    env_file: .env
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_DATABASE: $DB_DATABASE
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - ./backend:/my-contacts/backend
      - node_modules:/my-contacts/backend/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Postgres database mounted to local filesystem
  database:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DATABASE
    volumes:
      # Bind mounts to local filesystem for persistence during local development
      - type: bind
        source: ./database/data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database/initdb
        target: /docker-entrypoint-initdb.d
    networks:
      - app-network
    ports:
      - "5432:5432"

volumes:
  # named volume
  node_modules:

networks:
  app-network:
    driver: bridge
