name: my-contacts
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/my-contacts/backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database
    restart: always

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mycontacts_pw
      POSTGRES_USER: mycontacts_user
      POSTGRES_DB: mycontacts_db
    volumes:
      - type: bind
        source: ./database/data
        target: /var/lib/postgres/data
        bind:
          create_host_path: true
      - ./database/initdb:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    restart: always
